id: I7E8EB09E
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:15:38.745531
last_modified: 2023-02-08 15:15:38.745685
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: sa
bases:
  44CB:
    base_file: 44CB.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
